---
# handlers file for ivansible.letsencrypt_copy

- name: remove temporary certbot archive on master
  file:
    path: "{{ le_master_archive.path }}"
    state: absent
  delegate_to: "{{ certbot_master_host }}"

- name: remove temporary certbot archive on controller
  file:
    path: "{{ le_controller_archive.path }}"
    state: absent
  connection: local

- name: run certbot update script once
  command: "{{ certbot_update_script }}"
  become: yes
  ignore_errors: yes
...
